import { useSettings } from "../SettingsContext";
import { SettingsRow } from "../SettingsRow";

const resolveKey = (source: Record<string, unknown>, key: string): unknown => {
  const parts = key.split(".");
  let value: unknown = source;

  for (const part of parts) {
    if (value == null || typeof value !== "object") return undefined;
    value = (value as Record<string, unknown>)[part];
  }

  return value;
};

const getSettingValue = (
  draft: Record<string, unknown>,
  config: Record<string, unknown>,
  key: string
): unknown => {
  if (key in draft) return draft[key];
  const draftNestedValue = resolveKey(draft, key);
  if (draftNestedValue !== undefined) return draftNestedValue;
  if (key in config) return config[key];
  return resolveKey(config, key);
};

export function EditingTab() {
  const { config, draft, updateSetting } = useSettings();
  const get = (key: string) =>
    getSettingValue(draft as Record<string, unknown>, config as Record<string, unknown>, key) as
      | string
      | boolean
      | number
      | undefined;

  const fuzzyMatch = get("edit.fuzzyMatch") ?? true;
  const lspEnabled = get("lsp.enabled") ?? true;

  return (
    <div>
      {/* § Edit Tool */}
      <div className="omp-settings-section">
        <h3 className="omp-settings-section-title">Edit Tool</h3>
        <p className="omp-settings-section-desc">File editing tool configuration</p>
        <SettingsRow title="Mode" description="Edit tool strategy">
          <select
            className="omp-settings-select"
            value={String(get("edit.mode") ?? "hashline")}
            onChange={(e) => updateSetting("edit.mode", e.target.value)}
          >
            <option value="hashline">Hashline</option>
            <option value="replace">Replace</option>
            <option value="patch">Patch</option>
            <option value="vim">Vim</option>
            <option value="apply_patch">Apply Patch</option>
          </select>
        </SettingsRow>
        <SettingsRow title="Fuzzy Match" description="Accept fuzzy matches for whitespace differences">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!fuzzyMatch}
            onChange={(e) => updateSetting("edit.fuzzyMatch", e.target.checked)}
          />
        </SettingsRow>
        {!!fuzzyMatch && (
          <SettingsRow title="Fuzzy Threshold" description="Minimum similarity score for fuzzy match">
            <select
              className="omp-settings-select"
              value={String(get("edit.fuzzyThreshold") ?? 0.95)}
              onChange={(e) => updateSetting("edit.fuzzyThreshold", Number(e.target.value))}
            >
              <option value="0.85">0.85</option>
              <option value="0.9">0.90</option>
              <option value="0.95">0.95</option>
              <option value="0.98">0.98</option>
            </select>
          </SettingsRow>
        )}
        <SettingsRow title="Streaming Abort" description="Abort operation on failed patch preview">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("edit.streamingAbort") ?? false)}
            onChange={(e) => updateSetting("edit.streamingAbort", e.target.checked)}
          />
        </SettingsRow>
        <SettingsRow title="Block Auto-Generated" description="Prevent editing auto-generated files" last>
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("edit.blockAutoGenerated") ?? true)}
            onChange={(e) => updateSetting("edit.blockAutoGenerated", e.target.checked)}
          />
        </SettingsRow>
      </div>

      {/* § Read Tool */}
      <div className="omp-settings-section">
        <h3 className="omp-settings-section-title">Read Tool</h3>
        <p className="omp-settings-section-desc">File reading tool configuration</p>
        <SettingsRow title="Line Numbers" description="Prepend line numbers to read output">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("readLineNumbers") ?? false)}
            onChange={(e) => updateSetting("readLineNumbers", e.target.checked)}
          />
        </SettingsRow>
        <SettingsRow title="Hash Lines" description="Include line hashes for hashline anchoring">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("readHashLines") ?? true)}
            onChange={(e) => updateSetting("readHashLines", e.target.checked)}
          />
        </SettingsRow>
        <SettingsRow title="Default Limit" description="Default lines returned per read">
          <select
            className="omp-settings-select"
            value={String(get("read.defaultLimit") ?? 500)}
            onChange={(e) => updateSetting("read.defaultLimit", Number(e.target.value))}
          >
            <option value="200">200</option>
            <option value="300">300</option>
            <option value="500">500</option>
            <option value="1000">1000</option>
            <option value="5000">5000</option>
          </select>
        </SettingsRow>
        <SettingsRow title="Tool Result Preview" description="Render read results inline in transcript" last>
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("read.toolResultPreview") ?? false)}
            onChange={(e) => updateSetting("read.toolResultPreview", e.target.checked)}
          />
        </SettingsRow>
      </div>

      {/* § LSP */}
      <div className="omp-settings-section">
        <h3 className="omp-settings-section-title">LSP</h3>
        <p className="omp-settings-section-desc">Language Server Protocol integration</p>
        <SettingsRow title="Enabled" description="Enable LSP integration tool" last={!lspEnabled}>
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!lspEnabled}
            onChange={(e) => updateSetting("lsp.enabled", e.target.checked)}
          />
        </SettingsRow>
        {!!lspEnabled && (
          <>
            <SettingsRow title="Format on Write" description="Auto-format files after agent writes">
              <input
                type="checkbox"
                className="omp-settings-toggle"
                checked={!!(get("lsp.formatOnWrite") ?? false)}
                onChange={(e) => updateSetting("lsp.formatOnWrite", e.target.checked)}
              />
            </SettingsRow>
            <SettingsRow title="Diagnostics on Write" description="Return diagnostics after file write">
              <input
                type="checkbox"
                className="omp-settings-toggle"
                checked={!!(get("lsp.diagnosticsOnWrite") ?? true)}
                onChange={(e) => updateSetting("lsp.diagnosticsOnWrite", e.target.checked)}
              />
            </SettingsRow>
            <SettingsRow title="Diagnostics on Edit" description="Return diagnostics after file edit" last>
              <input
                type="checkbox"
                className="omp-settings-toggle"
                checked={!!(get("lsp.diagnosticsOnEdit") ?? false)}
                onChange={(e) => updateSetting("lsp.diagnosticsOnEdit", e.target.checked)}
              />
            </SettingsRow>
          </>
        )}
      </div>

      {/* § Shell Processing */}
      <div className="omp-settings-section">
        <h3 className="omp-settings-section-title">Shell Processing</h3>
        <p className="omp-settings-section-desc">Shell command interception and output processing</p>
        <SettingsRow title="Bash Interceptor" description="Block shell commands that have dedicated tools">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("bashInterceptor.enabled") ?? false)}
            onChange={(e) => updateSetting("bashInterceptor.enabled", e.target.checked)}
          />
        </SettingsRow>
        <SettingsRow title="Shell Minimizer" description="Compress verbose shell output" last>
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("shellMinimizer.enabled") ?? true)}
            onChange={(e) => updateSetting("shellMinimizer.enabled", e.target.checked)}
          />
        </SettingsRow>
      </div>

      {/* § Eval */}
      <div className="omp-settings-section">
        <h3 className="omp-settings-section-title">Eval</h3>
        <p className="omp-settings-section-desc">Code evaluation kernel configuration</p>
        <SettingsRow title="Python" description="Enable Python eval cells">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("eval.py") ?? true)}
            onChange={(e) => updateSetting("eval.py", e.target.checked)}
          />
        </SettingsRow>
        <SettingsRow title="JavaScript" description="Enable JavaScript eval cells">
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("eval.js") ?? true)}
            onChange={(e) => updateSetting("eval.js", e.target.checked)}
          />
        </SettingsRow>
        <SettingsRow title="Kernel Mode" description="IPython kernel lifecycle">
          <select
            className="omp-settings-select"
            value={String(get("python.kernelMode") ?? "session")}
            onChange={(e) => updateSetting("python.kernelMode", e.target.value)}
          >
            <option value="session">Session</option>
            <option value="per-call">Per-call</option>
          </select>
        </SettingsRow>
        <SettingsRow title="Shared Gateway" description="Share IPython kernel across instances" last>
          <input
            type="checkbox"
            className="omp-settings-toggle"
            checked={!!(get("python.sharedGateway") ?? true)}
            onChange={(e) => updateSetting("python.sharedGateway", e.target.checked)}
          />
        </SettingsRow>
      </div>
    </div>
  );
}
